# Glow v2.0+ config with built-in Tokyo Night theme
style: "tokyo-night"
width: 100
local: false
mouse: true
pager: true

# Ensure proper rendering
show_all_files: false
glamour:
  document:
    margin: 0
  heading:
    bold: true