version: '3.8'

services:
  # Terminal container
  terminal:
    build:
      context: .
      dockerfile: container/Dockerfile
    image: terminal-portfolio:latest
    container_name: terminal-portfolio
    ports:
      - "2222:22"  # SSH access (if needed)
    tty: true
    stdin_open: true
    environment:
      - TERM=xterm-256color
    volumes:
      - terminal_data:/home/portfolio/projects
    networks:
      - terminal-network

  # Backend API server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: terminal-backend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - TERMINAL_CONTAINER=terminal-portfolio
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock  # For Docker API access
    networks:
      - terminal-network
    depends_on:
      - terminal

  # Frontend Next.js app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: terminal-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - terminal-network
    depends_on:
      - backend

volumes:
  terminal_data:

networks:
  terminal-network:
    driver: bridge