services:
  nginx:
    ports: !override
      - "8088:80"
    volumes: !override
      - ./nginx-local.conf:/etc/nginx/nginx.conf:ro

  frontend:
    platform: linux/amd64

  backend:
    platform: linux/amd64

  socket-proxy:
    platform: linux/amd64
