app = "term-site-backend"
primary_region = "iad"

[build]
  dockerfile = "backend/Dockerfile"

[experimental]
  enable_docker = true

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  NODE_ENV = "production"
  PORT = "3000"
  DOCKER_HOST = "unix:///var/run/docker.sock"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[mounts]
  source = "docker_data"
  destination = "/var/lib/docker"