#!/bin/bash
source "$(dirname "$0")/shared-functions.sh"

echo ""
typewriter "${GREEN}commands${RESET}"
animated_separator "-" 10 "$GREEN"
typewriter "${YELLOW}  about       ${WHITE}learn about me${RESET}"
typewriter "${YELLOW}  contact     ${WHITE}my email and links to socials${RESET}"
typewriter "${YELLOW}  projects    ${WHITE}explore my projects (you can use vim!)${RESET}"
typewriter "${YELLOW}  blog        ${WHITE}view my blog${RESET}"
typewriter "${YELLOW}  help        ${WHITE}you already used it once...${RESET}"
typewriter "${YELLOW}  home        ${WHITE}back to the main page!${RESET}"
echo""
typewriter "${DIM}you can use most commands you are familiar with inside the terminal like cd, ls, etc.${RESET}"
typewriter "${DIM}other tools like ${CYAN}nvim${RESET}${DIM}, ${CYAN}git${RESET}${DIM}, ${CYAN}grep${RESET}${DIM}, ${CYAN}figlet${RESET}${DIM} and many more are available!${RESET}"
echo ""
