// Terminal theme: Mathias
// Auto-generated by scripts/generate-theme.sh — do not edit by hand.
// Re-run after changing your Ghostty theme: ./scripts/generate-theme.sh

export const terminalTheme = {
  background: '#000000',
  foreground: '#bbbbbb',
  cursor: '#bbbbbb',
  cursorAccent: '#ffffff',
  selection: '#555555',
  selectionForeground: '#f2f2f2',

  black:         '#000000',   // colour0
  red:           '#e52222',   // colour1
  green:         '#a6e32d',   // colour2
  yellow:        '#fc951e',   // colour3
  blue:          '#c48dff',   // colour4
  magenta:       '#fa2573',   // colour5
  cyan:          '#67d9f0',   // colour6
  white:         '#f2f2f2',   // colour7

  brightBlack:   '#555555',   // colour8
  brightRed:     '#ff5555',   // colour9
  brightGreen:   '#55ff55',  // colour10
  brightYellow:  '#ffff55',  // colour11
  brightBlue:    '#5555ff',  // colour12
  brightMagenta: '#ff55ff',  // colour13
  brightCyan:    '#55ffff',  // colour14
  brightWhite:   '#ffffff',  // colour15
};

export const terminalConfig = {
  fontFamily: '"JetBrainsMono Nerd Font Mono", "JetBrainsMono Nerd Font", "JetBrains Mono", "Fira Code", "Monaco", "Consolas", monospace',
  fontSize: 12,
  fontWeight: 'normal' as const,
  fontWeightBold: 'bold' as const,
  lineHeight: 1.0,

  cursorBlink: true,
  cursorStyle: 'block' as const,
  bellStyle: 'none' as const,

  scrollback: 10000,
  fastScrollModifier: 'alt' as const,

  allowProposedApi: true,
  allowTransparency: false,
  macOptionIsMeta: true,

  cols: 120,
  rows: 30,

  theme: terminalTheme,
};
