// Terminal theme: LiquidCarbonTransparent
// Auto-generated by scripts/generate-theme.sh — do not edit by hand.
// Re-run after changing your Ghostty theme: ./scripts/generate-theme.sh

export const terminalTheme = {
  background: '#000000',
  foreground: '#afc2c2',
  cursor: '#ffffff',
  cursorAccent: '#000000',
  selection: '#7dbeff',
  selectionForeground: '#000000',

  black:         '#000000',   // colour0
  red:           '#ff3030',   // colour1
  green:         '#559a70',   // colour2
  yellow:        '#ccac00',   // colour3
  blue:          '#0099cc',   // colour4
  magenta:       '#cc69c8',   // colour5
  cyan:          '#7ac4cc',   // colour6
  white:         '#bccccc',   // colour7

  brightBlack:   '#000000',   // colour8
  brightRed:     '#ff3030',   // colour9
  brightGreen:   '#559a70',  // colour10
  brightYellow:  '#ccac00',  // colour11
  brightBlue:    '#0099cc',  // colour12
  brightMagenta: '#cc69c8',  // colour13
  brightCyan:    '#7ac4cc',  // colour14
  brightWhite:   '#bccccc',  // colour15
};

export const terminalConfig = {
  fontFamily: '"JetBrainsMono Nerd Font Mono", "JetBrainsMono Nerd Font", "JetBrains Mono", "Fira Code", "Monaco", "Consolas", monospace',
  fontSize: 12,
  fontWeight: 'normal' as const,
  fontWeightBold: 'bold' as const,
  lineHeight: 1.0,

  cursorBlink: true,
  cursorStyle: 'block' as const,
  bellStyle: 'none' as const,

  scrollback: 10000,
  fastScrollModifier: 'alt' as const,

  allowProposedApi: true,
  allowTransparency: false,
  macOptionIsMeta: true,

  cols: 120,
  rows: 30,

  theme: terminalTheme,
};
