name: Deploy

on:
  push:
    branches: [main, develop, 'feature/*']
  pull_request:
    branches: [main]

jobs:
  build-terminal-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build terminal image
        run: |
          # Show what files we're building with
          echo "Files in container directory:"
          ls -la container/
          echo "Content of welcome.sh (first 10 lines):"
          head -n 10 container/welcome.sh
          
          # Build the terminal image with no cache to ensure latest changes
          docker build --no-cache -f container/Dockerfile -t terminal-portfolio:latest .
          
          # Verify the welcome script is in the image
          echo "Verifying welcome.sh in built image:"
          docker run --rm terminal-portfolio:latest head -n 5 /home/portfolio/scripts/welcome.sh
          
          # Tag for Docker Hub with both latest and a unique tag
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          docker tag terminal-portfolio:latest ${{ secrets.DOCKER_USERNAME }}/terminal-portfolio:latest
          docker tag terminal-portfolio:latest ${{ secrets.DOCKER_USERNAME }}/terminal-portfolio:$TIMESTAMP
          
          # Push both tags to registry
          docker push ${{ secrets.DOCKER_USERNAME }}/terminal-portfolio:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/terminal-portfolio:$TIMESTAMP
          
          echo "Built and pushed image with timestamp: $TIMESTAMP"

  deploy-backend:
    needs: build-terminal-image
    runs-on: ubuntu-latest
    outputs:
      backend-url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy to Fly.io
        id: deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            APP_NAME="term-site-backend"
          else
            # Create branch-specific app name
            BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g' | cut -c1-20)
            APP_NAME="term-site-backend-${BRANCH_NAME}"
            
            # Check if app exists, create if not
            flyctl apps list | grep -q "$APP_NAME" || flyctl apps create "$APP_NAME" --org personal
          fi
          
          # Deploy
          flyctl deploy --app "$APP_NAME" --ha=false
          
          # Get URL
          URL="https://${APP_NAME}.fly.dev"
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "Deployed to: $URL"
      
      
  deploy-frontend:
    needs: deploy-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Vercel
        working-directory: ./frontend
        run: |
          npm i -g vercel
          
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes \
              --env NEXT_PUBLIC_API_URL=${{ needs.deploy-backend.outputs.backend-url }}
          else
            vercel --token=${{ secrets.VERCEL_TOKEN }} --yes \
              --env NEXT_PUBLIC_API_URL=${{ needs.deploy-backend.outputs.backend-url }}
          fi